project_id = "wsibvneidsmtsazfbmgc"

[functions.convert-pdf-to-image]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false

[functions.send-email-status]
verify_jwt = false

[functions.send-status-email-cron]
verify_jwt = false

[functions.unsubscribe-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.extract-signature]
verify_jwt = false

[functions.generate-card-gotenberg]
verify_jwt = false

[functions.generate-card-pdfs]
verify_jwt = false

[functions.generate-card-previews]
verify_jwt = false

[functions.generate-template-pdf]
verify_jwt = false

[functions.serve-pdf]
verify_jwt = false

[functions.test-mailgun]
verify_jwt = false